### ISSUE TITLE
SegFault on exit

### ISSUE THREAD

**Issue by eile** [BlueBrain/Livre#327]
Ubuntu 16.04 / Eq and Livre master:

```
gdb ../build/bin/livre
[...]
31430.Draw0     ../Collage/co/connection.cpp:111   10323 co::Connection 0x7fffa448ce40 state closed description NONE#0###0#default#: 0 MB out, 0 MB in
[Thread 0x7fffad162700 (LWP 31445) exited]
[Thread 0x7fff7dffb700 (LWP 31460) exited]
[Thread 0x7fff7e7fc700 (LWP 31459) exited]
31430.Draw0        ../Equalizer/eq/frame.cpp:40    10332 FrameData attached in frame destructor
[Thread 0x7fff7effd700 (LWP 31458) exited]

Thread 18 "Draw0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9cd79700 (LWP 31454)]
0x00007fffee8d497d in XQueryExtension () from /usr/lib/x86_64-linux-gnu/libX11.so.6
(gdb) bt
#0  0x00007fffee8d497d in XQueryExtension () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007fffee8c84f2 in XInitExtension () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#2  0x00007fffee69bfdf in XextAddDisplay () from /usr/lib/x86_64-linux-gnu/libXext.so.6
#3  0x00007fffc49a7f57 in ?? () from /usr/lib/nvidia-361/libGLX_nvidia.so.0
#4  0x00007fffc49a93ca in ?? () from /usr/lib/nvidia-361/libGLX_nvidia.so.0
#5  0x00007fffc49a9bba in ?? () from /usr/lib/nvidia-361/libGLX_nvidia.so.0
#6  0x00007fffc49aa565 in ?? () from /usr/lib/nvidia-361/libGLX_nvidia.so.0
#7  0x00007fffeae85023 in ?? () from /usr/lib/nvidia-361/libGLX.so.0
#8  0x00007fffeae855c1 in ?? () from /usr/lib/nvidia-361/libGLX.so.0
#9  0x00007ffff657cc3e in eq::glx::Window::doneCurrent (this=0x7fff84001230) at ../Equalizer/eq/glx/window.cpp:802
#10 0x00007ffff7b822ce in livre::EqContext::doneCurrent (this=0x7fff84000ad0) at ../Livre/livre/eq/render/EqContext.cpp:99
#11 0x00007ffff72327da in livre::Workers::Impl::execute (this=0x7fffa41e7fc0) at ../Livre/livre/core/pipeline/Workers.cpp:65
#12 0x00007ffff72340d5 in boost::_mfi::mf0<void, livre::Workers::Impl>::operator() (this=0x7fffa41e8628, p=0x7fffa41e7fc0)
    at /usr/include/boost/bind/mem_fn_template.hpp:49
#13 0x00007ffff7234038 in boost::_bi::list1<boost::_bi::value<livre::Workers::Impl*> >::operator()<boost::_mfi::mf0<void, livre::Workers::Impl>, boost::_bi::list0> (this=0x7fffa41e8638, f=..., a=...) at /usr/include/boost/bind/bind.hpp:253
#14 0x00007ffff7233fd0 in boost::_bi::bind_t<void, boost::_mfi::mf0<void, livre::Workers::Impl>, boost::_bi::list1<boost::_bi::value<livre::Workers::Impl*> > >::operator() (this=0x7fffa41e8628) at /usr/include/boost/bind/bind.hpp:893
#15 0x00007ffff7233f82 in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, livre::Workers::Impl>, boost::_bi::list1<boost::_bi::value<livre::Workers::Impl*> > > >::run (this=0x7fffa41e8470) at /usr/include/boost/thread/detail/thread.hpp:116
#16 0x00007ffff470f5d5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
#17 0x00007ffff33216fa in start_thread (arg=0x7fff9cd79700) at pthread_create.c:333
#18 0x00007ffff3057b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)  
```

**Comment by tribal-tec** [comment]
Fixed in https://github.com/BlueBrain/Livre/commit/e3b50b70d3cc952023673844f733e3439400ea27
